Prompt:
  Title: "请根据以下长文本生成一个合适的标题，不需要书名号，长度10字内："
  KnoledgeRAG: "使用以上下文来回答用户的问题。如果你不知道答案，就说你不知道。总是使用中文回答。
        问题: {question}
        可参考的上下文：
        ···
        {context}
        ···
        如果给定的上下文无法让你做出回答，请回答知识库中没有这个内容，你不知道。"